url: "https://adipurnm.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
analytics_url: https://stats.adipurnm.my.id/script.js
analytics_enabled: true
donate_url: "https://shop.adipurnm.com/supports"
title: "adipurnm's log" # the name of your site, e.g. ACME Corp.
email: "adi@adipurnm.com"
tagline: ""
description: kebun digital
author: Adi Purnama
twitter:
  card: summary
  username: adi_prnm
logo: /assets/images/adi-small.webp
social:
  name: Adi Purnama
  links:
  - https://twitter.com/adi_prnm
  - https://github.com/adiprnm
  - https://linkedin.com/in/adi-prnm
google_site_verification: google-site-verification=IiH3Ofey8Y2cbvKc6dp_yCPsEF9Hlk3zScc2LtxsHwk
locale: en_US
permalink: /:title
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/adi-og.jpg
collections:
  digital_awarenesses:
    output: true
guestbook_provider: "self_host"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
